JavaDoc Error Fix
error: no tag name after @
[ERROR]      * Returns true if the client currently owns the lock with {@param key} and {@param sortKey}. It returns false otherwise.

Fixing the above error where JavaDoc is unable to compile due to expecting something in the {@ so just got rid of the curly braces